kind = "DojoContract"
class_hash = "0x602e2e5b9a7ae2a87dab906ee8c4e327d64044569f0a073ba54395c1ba3c505"
original_class_hash = "0x602e2e5b9a7ae2a87dab906ee8c4e327d64044569f0a073ba54395c1ba3c505"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/risingrevenant_contracts_payment_payment_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::payment::payment_actions"
