kind = "DojoContract"
class_hash = "0x3e83ba247157de33e7bb7c072305ed80d7c4ea23c48c5521eea4ad2492f112a"
original_class_hash = "0x3e83ba247157de33e7bb7c072305ed80d7c4ea23c48c5521eea4ad2492f112a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/risingrevenant_contracts_trade_reinforcement_trade_reinforcement_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::trade_reinforcement::trade_reinforcement_actions"
