kind = "DojoContract"
class_hash = "0x50577d88d554b7365060e12df3e7bb16915954e37c0b47316decce50f8dd915"
original_class_hash = "0x50577d88d554b7365060e12df3e7bb16915954e37c0b47316decce50f8dd915"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/risingrevenant_contracts_outpost_outpost_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::outpost::outpost_actions"
