kind = "DojoContract"
class_hash = "0x421a31bf48a12d553109ce362e3ed8449cfbd3b6602be0960ff9a438ffd170c"
original_class_hash = "0x421a31bf48a12d553109ce362e3ed8449cfbd3b6602be0960ff9a438ffd170c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/risingrevenant_contracts_game_game_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::game::game_actions"
