kind = "DojoContract"
class_hash = "0xbd773a8243e3142b33bb0b50632efe48a8667b383028a147c1265eabad60ff"
original_class_hash = "0xbd773a8243e3142b33bb0b50632efe48a8667b383028a147c1265eabad60ff"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/risingrevenant_contracts_trade_outpost_trade_outpost_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::trade_outpost::trade_outpost_actions"
