kind = "DojoContract"
class_hash = "0x36c479205ac278f96fd0483d9716d0ac9766845b5dfdf60251f31535bdf3f48"
original_class_hash = "0x36c479205ac278f96fd0483d9716d0ac9766845b5dfdf60251f31535bdf3f48"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/risingrevenant_contracts_world_event_world_event_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::world_event::world_event_actions"
