kind = "DojoContract"
class_hash = "0x3a75b201831c1425e70f31c62355705f40857c958d7e7a9ee7d913e7ae81141"
original_class_hash = "0x3a75b201831c1425e70f31c62355705f40857c958d7e7a9ee7d913e7ae81141"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/risingrevenant_contracts_world_event_world_event_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::world_event::world_event_actions"
