kind = "DojoContract"
class_hash = "0x24ad026f5a7ed132171a28b15298f7d4c6b320100c98b639a4ee3e8d9ae17ff"
original_class_hash = "0x24ad026f5a7ed132171a28b15298f7d4c6b320100c98b639a4ee3e8d9ae17ff"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/risingrevenant_contracts_game_game_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::game::game_actions"
