kind = "DojoContract"
class_hash = "0x4bf2ae2c8de35bc91a49e9996762f8fad9f63f91efbc385c4db2ad8c9cd542a"
original_class_hash = "0x4bf2ae2c8de35bc91a49e9996762f8fad9f63f91efbc385c4db2ad8c9cd542a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/risingrevenant_contracts_reinforcement_reinforcement_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::reinforcement::reinforcement_actions"
