[world]
name = "rising-revenant"
seed = "rising-revenant-0.4.0"

[namespace]
default = "rising_revenant"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x058e3B49d870f08C96a02f794C82b5f6C868c074DeaDD6bA04E8d2194723B5bd"
