[world]
name = "rising-revenant"
seed = "rising-revenant-0.9.0"

[namespace]
default = "rising_revenant"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x058e3b49d870f08c96a02f794c82b5f6c868c074deadd6ba04e8d2194723b5bd"
keystore_path = "/home/ben/sn-accounts/0x058e3b49d870f08c96a02f794c82b5f6c868c074deadd6ba04e8d2194723b5bd-keystore.json"

[init_call_args]
"rising_revenant-game_actions" = []

[writers]

"rising_revenant-GameName" = ["rising_revenant-game_actions"]
"rising_revenant-GameClassHash" = ["rising_revenant-game_actions"]
"rising_revenant-GameContractAddress" = ["rising_revenant-game_actions"]
"rising_revenant-FortificationTokens" = ["rising_revenant-game_actions"]
"rising_revenant-ContributionWeight" = ["rising_revenant-game_actions"]
"rising_revenant-GamePhases" = ["rising_revenant-game_actions"]
"rising_revenant-MapSize" = ["rising_revenant-game_actions"]
"rising_revenant-Permission" = ["rising_revenant-game_actions"]
"rising_revenant-WorldEventMinInterval" = ["rising_revenant-game_actions"]
"rising_revenant-WorldEventSetup" = ["rising_revenant-game_actions"]
"rising_revenant-OutpostSetup" = ["rising_revenant-game_actions"]
"rising_revenant-Winner" = ["rising_revenant-game_actions"]

"rising_revenant-CarePackage" = ["rising_revenant-care_package_actions"]
"rising_revenant-CarePackageContents" = ["rising_revenant-care_package_actions"]
"rising_revenant-CarePackageSold" = ["rising_revenant-care_package_actions"]
"rising_revenant-CarePackageMarket" = [
    "rising_revenant-game_actions",
    "rising_revenant-care_package_actions",
]

"rising_revenant-Map" = ["rising_revenant-outpost_actions"]
"rising_revenant-Outpost" = ["rising_revenant-outpost_actions"]
"rising_revenant-OutpostEvent" = ["rising_revenant-outpost_actions"]
"rising_revenant-OutpostsActive" = ["rising_revenant-outpost_actions"]

"rising_revenant-CurrentEvent" = ["rising_revenant-world_event_actions"]
"rising_revenant-LastEventOfType" = ["rising_revenant-world_event_actions"]
"rising_revenant-WorldEventEvent" = ["rising_revenant-world_event_actions"]

"rising_revenant-UserContribution" = [
    "rising_revenant-outpost_actions",
    "rising_revenant-world_event_actions",
]

"rising_revenant-GamePot" = [
    "rising_revenant-game_actions",
    "rising_revenant-care_package_actions",
    "rising_revenant-outpost_actions",
]
