[package]
cairo-version = "=2.9.2"
name = "rising_revenant"
version = "0.5.3"


[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true

[dependencies]
starknet = "2.9.2"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.1.2" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.19.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.19.0" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.19.0" }
cubit = { git = "https://github.com/bengineer42/cubit", tag = "cairo--2.8.0" }
# cartridge_vrf = { git = "https://github.com/cartridge-gg/vrf-server" }

[dev-dependencies]
cairo_test = "=2.9.2"

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = ["dojo::world::world_contract::world"]


[profile.sepolia]

[features]
default = []
