[package]
cairo-version = "2.8.4"
name = "rr_tokens"
version = "0.1.0"

[requirments]
starknet = "2.8.4"


[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true

[lib]

[[target.starknet-contract]]
sierra = true
