[package]
cairo-version = "^2.7.0"
name = "rr_tokens"
version = "0.1.0"

[requirments]
starknet = "^2.7.0"


[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true

[lib]

[[target.starknet-contract]]
sierra = true
