kind = "DojoContract"
class_hash = "0x2f8a7e54491db3083000550f09f2bb50da45ef29219576bdf7f1e2ef58c3937"
original_class_hash = "0x2f8a7e54491db3083000550f09f2bb50da45ef29219576bdf7f1e2ef58c3937"
base_class_hash = "0x0"
abi = "manifests/sepolia/abis/base/contracts/risingrevenant_contracts_trade_reinforcement_trade_reinforcement_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::trade_reinforcement::trade_reinforcement_actions"
