kind = "DojoContract"
class_hash = "0x75290fce32a88d116fae491f6eecf1de43a786344384b94c11a8159bcb76766"
original_class_hash = "0x75290fce32a88d116fae491f6eecf1de43a786344384b94c11a8159bcb76766"
base_class_hash = "0x0"
abi = "manifests/sepolia/abis/base/contracts/risingrevenant_contracts_outpost_outpost_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::outpost::outpost_actions"
