[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x403df785de33e6f468419bf138db7ccaccfbd6801e13e452a252df38b2b9657"
transaction_hash = "0x10d470c733841f5a9d4585e7b8b43b5786fe0487fc64dce036a46092b32281f"
block_number = 13
seed = "risingrevenant"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x796bdacfdd83b316cb83560f2e0a471b37acc9b851af2dd0ce9c51668ea2b6d"
class_hash = "0x269266edc3ad1796ddd92a66866d3002a9f7a66ef7d92aec9a0289a612d57f5"
original_class_hash = "0x269266edc3ad1796ddd92a66866d3002a9f7a66ef7d92aec9a0289a612d57f5"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/risingrevenant_contracts_game_game_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::game::game_actions"

[[contracts]]
kind = "DojoContract"
address = "0x5e2e39c65bb8f60f2976796a304644a097b6201f810b6b2745ae03d90004937"
class_hash = "0x50577d88d554b7365060e12df3e7bb16915954e37c0b47316decce50f8dd915"
original_class_hash = "0x50577d88d554b7365060e12df3e7bb16915954e37c0b47316decce50f8dd915"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/risingrevenant_contracts_outpost_outpost_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::outpost::outpost_actions"

[[contracts]]
kind = "DojoContract"
address = "0x6ee2ef201d285ad87fa639427d35ac55b5af466ba9db1e2f5730e69bb81256d"
class_hash = "0x4bf2ae2c8de35bc91a49e9996762f8fad9f63f91efbc385c4db2ad8c9cd542a"
original_class_hash = "0x4bf2ae2c8de35bc91a49e9996762f8fad9f63f91efbc385c4db2ad8c9cd542a"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/risingrevenant_contracts_reinforcement_reinforcement_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::reinforcement::reinforcement_actions"

[[contracts]]
kind = "DojoContract"
address = "0x257c0538f358fd138fe4c8d5df0620ce4c7539fa2b5bc7e19284eb2ddb2b562"
class_hash = "0xbd773a8243e3142b33bb0b50632efe48a8667b383028a147c1265eabad60ff"
original_class_hash = "0xbd773a8243e3142b33bb0b50632efe48a8667b383028a147c1265eabad60ff"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/risingrevenant_contracts_trade_outpost_trade_outpost_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::trade_outpost::trade_outpost_actions"

[[contracts]]
kind = "DojoContract"
address = "0x2c85167ce5857a532fb23ef55fae7cb6a3cd2e81992c7ff0d6c691e83954580"
class_hash = "0x3e83ba247157de33e7bb7c072305ed80d7c4ea23c48c5521eea4ad2492f112a"
original_class_hash = "0x3e83ba247157de33e7bb7c072305ed80d7c4ea23c48c5521eea4ad2492f112a"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/risingrevenant_contracts_trade_reinforcement_trade_reinforcement_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::trade_reinforcement::trade_reinforcement_actions"

[[contracts]]
kind = "DojoContract"
address = "0xf15c94a9264d8a8b520ebd1a6ffd337758034bd5062c9c42f4b67163a9ad7c"
class_hash = "0x3a75b201831c1425e70f31c62355705f40857c958d7e7a9ee7d913e7ae81141"
original_class_hash = "0x3a75b201831c1425e70f31c62355705f40857c958d7e7a9ee7d913e7ae81141"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/risingrevenant_contracts_world_event_world_event_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "risingrevenant::contracts::world_event::world_event_actions"

[[models]]
kind = "DojoModel"
class_hash = "0x7e4f76150c23bc5cb8da037bb334623345d61b8b6333b1cca3fa3fd152eb02e"
original_class_hash = "0x7e4f76150c23bc5cb8da037bb334623345d61b8b6333b1cca3fa3fd152eb02e"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_game_current_game.json"
name = "risingrevenant::components::game::current_game"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "game_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x12cd74836f89d8f1febd9ff782dfacdaaa614e560a79c70e3ed9df6202973b4"
original_class_hash = "0x12cd74836f89d8f1febd9ff782dfacdaaa614e560a79c70e3ed9df6202973b4"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_game_dev_wallet.json"
name = "risingrevenant::components::game::dev_wallet"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "balance"
type = "u256"
key = false

[[models.members]]
name = "init"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7184627466500b8560692db8ab27015172aa0c1cb4414b53afc2395f75a62f"
original_class_hash = "0x7184627466500b8560692db8ab27015172aa0c1cb4414b53afc2395f75a62f"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_game_game_erc_20.json"
name = "risingrevenant::components::game::game_erc_20"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1f95a8e629e208b060027f511d260b974cf5d095c55e239ca17804bba08c147"
original_class_hash = "0x1f95a8e629e208b060027f511d260b974cf5d095c55e239ca17804bba08c147"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_game_game_map.json"
name = "risingrevenant::components::game::game_map"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "dimensions"
type = "Dimensions"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x32ac8ff3cbe075aa286ab39ea5f43e7eac434c3383fa20eee57e6383fe62c4c"
original_class_hash = "0x32ac8ff3cbe075aa286ab39ea5f43e7eac434c3383fa20eee57e6383fe62c4c"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_game_game_phases.json"
name = "risingrevenant::components::game::game_phases"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "status"
type = "u8"
key = false

[[models.members]]
name = "preparation_block_number"
type = "u64"
key = false

[[models.members]]
name = "play_block_number"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7236e3209ddd4349dad74f0ca5ce8902949068815c5339dc626a3f7ac6cce82"
original_class_hash = "0x7236e3209ddd4349dad74f0ca5ce8902949068815c5339dc626a3f7ac6cce82"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_game_game_pot.json"
name = "risingrevenant::components::game::game_pot"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "total_pot"
type = "u256"
key = false

[[models.members]]
name = "winners_pot"
type = "u256"
key = false

[[models.members]]
name = "confirmation_pot"
type = "u256"
key = false

[[models.members]]
name = "ltr_pot"
type = "u256"
key = false

[[models.members]]
name = "dev_pot"
type = "u256"
key = false

[[models.members]]
name = "claimed"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4321c2af890408d51782c3dd6ff01eeefa8e071c12764d3d80a5b70d768fb2c"
original_class_hash = "0x4321c2af890408d51782c3dd6ff01eeefa8e071c12764d3d80a5b70d768fb2c"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_game_game_pot_consts.json"
name = "risingrevenant::components::game::game_pot_consts"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "pot_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "dev_percent"
type = "u8"
key = false

[[models.members]]
name = "confirmation_percent"
type = "u8"
key = false

[[models.members]]
name = "ltr_percent"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5ca9df4337ad01cd1d7b8e4e43d67ff0a29a6925b1e494e78c9f478154885f3"
original_class_hash = "0x5ca9df4337ad01cd1d7b8e4e43d67ff0a29a6925b1e494e78c9f478154885f3"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_game_game_state.json"
name = "risingrevenant::components::game::game_state"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "outpost_created_count"
type = "u32"
key = false

[[models.members]]
name = "outpost_remaining_count"
type = "u32"
key = false

[[models.members]]
name = "remain_life_count"
type = "u32"
key = false

[[models.members]]
name = "reinforcement_count"
type = "u32"
key = false

[[models.members]]
name = "contribution_score_total"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x59c6d5980c90f5a8b95a6d651877e385b48f826aac23f2ca21752b1cee8b75d"
original_class_hash = "0x59c6d5980c90f5a8b95a6d651877e385b48f826aac23f2ca21752b1cee8b75d"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_game_game_trade_tax.json"
name = "risingrevenant::components::game::game_trade_tax"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "trade_tax_percent"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x60c36bcc2828f2f0eb9681abbbddfce16c6a493626f8c7d22ed7d2dca57b1f3"
original_class_hash = "0x60c36bcc2828f2f0eb9681abbbddfce16c6a493626f8c7d22ed7d2dca57b1f3"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_outpost_outpost.json"
name = "risingrevenant::components::outpost::outpost"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "position"
type = "Position"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "life"
type = "u32"
key = false

[[models.members]]
name = "reinforces_remaining"
type = "u32"
key = false

[[models.members]]
name = "reinforcement_type"
type = "ReinforcementType"
key = false

[[models.members]]
name = "status"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x24aae2d4cbe62707981352c0f4be8f37617fabb29b098ba3f06f72e6fed5000"
original_class_hash = "0x24aae2d4cbe62707981352c0f4be8f37617fabb29b098ba3f06f72e6fed5000"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_outpost_outpost_market.json"
name = "risingrevenant::components::outpost::outpost_market"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "price"
type = "u256"
key = false

[[models.members]]
name = "max_sellable"
type = "u32"
key = false

[[models.members]]
name = "max_per_player"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x538b034b0f0f79dce20a59f63c54311748a0b358cd7f3c41224003ea9f48531"
original_class_hash = "0x538b034b0f0f79dce20a59f63c54311748a0b358cd7f3c41224003ea9f48531"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_outpost_outpost_setup.json"
name = "risingrevenant::components::outpost::outpost_setup"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "life"
type = "u32"
key = false

[[models.members]]
name = "max_reinforcements"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4f619b1c6827ded83bf4950d1949d07e4ea91b9c2e31a6e2ba5f09a6a5d9e15"
original_class_hash = "0x4f619b1c6827ded83bf4950d1949d07e4ea91b9c2e31a6e2ba5f09a6a5d9e15"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_player_player_contribution.json"
name = "risingrevenant::components::player::player_contribution"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "score"
type = "u256"
key = false

[[models.members]]
name = "claimed"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7c4bf23b9cf792870afb64ed26310d5b9c12bf8fb8204341c612a32f8289ecf"
original_class_hash = "0x7c4bf23b9cf792870afb64ed26310d5b9c12bf8fb8204341c612a32f8289ecf"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_player_player_info.json"
name = "risingrevenant::components::player::player_info"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "outpost_count"
type = "u32"
key = false

[[models.members]]
name = "reinforcements_available_count"
type = "u32"
key = false

[[models.members]]
name = "init"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x73b9456d1c1b0c8845497a4e767a9d267c870101e7998e1315a063620954b74"
original_class_hash = "0x73b9456d1c1b0c8845497a4e767a9d267c870101e7998e1315a063620954b74"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_reinforcement_reinforcement_market_consts.json"
name = "risingrevenant::components::reinforcement::reinforcement_market_consts"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "target_price"
type = "u128"
key = false

[[models.members]]
name = "decay_constant_mag"
type = "u128"
key = false

[[models.members]]
name = "max_sellable_percentage"
type = "u32"
key = false

[[models.members]]
name = "time_scale_mag_factor"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3618228ef8ba61db8ee0daa250ad9ea491c800b1f47190955e470af332f8198"
original_class_hash = "0x3618228ef8ba61db8ee0daa250ad9ea491c800b1f47190955e470af332f8198"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_trade_outpost_trade.json"
name = "risingrevenant::components::trade::outpost_trade"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "trade_id"
type = "u128"
key = true

[[models.members]]
name = "trade_type"
type = "u8"
key = false

[[models.members]]
name = "seller"
type = "ContractAddress"
key = false

[[models.members]]
name = "buyer"
type = "ContractAddress"
key = false

[[models.members]]
name = "price"
type = "u128"
key = false

[[models.members]]
name = "offer"
type = "Position"
key = false

[[models.members]]
name = "status"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x538e03f0507759c2cd336d1f81cd650d541943ed3878affc87daf58de134552"
original_class_hash = "0x538e03f0507759c2cd336d1f81cd650d541943ed3878affc87daf58de134552"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_trade_reinforcement_trade.json"
name = "risingrevenant::components::trade::reinforcement_trade"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "trade_id"
type = "u128"
key = true

[[models.members]]
name = "trade_type"
type = "u8"
key = false

[[models.members]]
name = "seller"
type = "ContractAddress"
key = false

[[models.members]]
name = "buyer"
type = "ContractAddress"
key = false

[[models.members]]
name = "price"
type = "u128"
key = false

[[models.members]]
name = "offer"
type = "u32"
key = false

[[models.members]]
name = "status"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4cde4bdc9c3ea163dade7dd42c51fdf8d8eede99cda52b4d96757c365714af9"
original_class_hash = "0x4cde4bdc9c3ea163dade7dd42c51fdf8d8eede99cda52b4d96757c365714af9"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_world_event_current_world_event.json"
name = "risingrevenant::components::world_event::current_world_event"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "event_id"
type = "u128"
key = false

[[models.members]]
name = "position"
type = "Position"
key = false

[[models.members]]
name = "event_type"
type = "EventType"
key = false

[[models.members]]
name = "radius"
type = "u32"
key = false

[[models.members]]
name = "number"
type = "u32"
key = false

[[models.members]]
name = "block_number"
type = "u64"
key = false

[[models.members]]
name = "previous_event"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2dd204a8425c24605677bc068b66c43b3a97db132acb8cff8b332fd7737006f"
original_class_hash = "0x2dd204a8425c24605677bc068b66c43b3a97db132acb8cff8b332fd7737006f"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_world_event_outpost_verified.json"
name = "risingrevenant::components::world_event::outpost_verified"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "event_id"
type = "u128"
key = true

[[models.members]]
name = "outpost_id"
type = "Position"
key = true

[[models.members]]
name = "verified"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x721dc5cb0eb9c1e21507b37697b9cf3932ab1400829ace0f9f17f976e5dbfc1"
original_class_hash = "0x721dc5cb0eb9c1e21507b37697b9cf3932ab1400829ace0f9f17f976e5dbfc1"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_world_event_world_event.json"
name = "risingrevenant::components::world_event::world_event"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "event_id"
type = "u128"
key = true

[[models.members]]
name = "position"
type = "Position"
key = false

[[models.members]]
name = "event_type"
type = "EventType"
key = false

[[models.members]]
name = "radius"
type = "u32"
key = false

[[models.members]]
name = "verifications"
type = "u32"
key = false

[[models.members]]
name = "number"
type = "u32"
key = false

[[models.members]]
name = "block_number"
type = "u64"
key = false

[[models.members]]
name = "previous_event"
type = "u128"
key = false

[[models.members]]
name = "next_event"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1dedcb93628b96887ec772b05fe9e07ce7b1d3c94c49634301539ac51bc8743"
original_class_hash = "0x1dedcb93628b96887ec772b05fe9e07ce7b1d3c94c49634301539ac51bc8743"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_world_event_world_event_setup.json"
name = "risingrevenant::components::world_event::world_event_setup"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "radius_start"
type = "u32"
key = false

[[models.members]]
name = "radius_increase"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4accc145f46385ee34e191100d0cf6acf1674ca7477c3009ba366603f961e76"
original_class_hash = "0x4accc145f46385ee34e191100d0cf6acf1674ca7477c3009ba366603f961e76"
abi = "manifests/dev/abis/deployments/models/risingrevenant_components_world_event_world_event_verifications.json"
name = "risingrevenant::components::world_event::world_event_verifications"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "verifications"
type = "u32"
key = false
