kind = "DojoModel"
class_hash = "0x4cde4bdc9c3ea163dade7dd42c51fdf8d8eede99cda52b4d96757c365714af9"
original_class_hash = "0x4cde4bdc9c3ea163dade7dd42c51fdf8d8eede99cda52b4d96757c365714af9"
abi = "manifests/sepolia/abis/base/models/risingrevenant_components_world_event_current_world_event.json"
name = "risingrevenant::components::world_event::current_world_event"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "event_id"
type = "u128"
key = false

[[members]]
name = "position"
type = "Position"
key = false

[[members]]
name = "event_type"
type = "EventType"
key = false

[[members]]
name = "radius"
type = "u32"
key = false

[[members]]
name = "number"
type = "u32"
key = false

[[members]]
name = "block_number"
type = "u64"
key = false

[[members]]
name = "previous_event"
type = "u128"
key = false
