kind = "DojoModel"
class_hash = "0x32ac8ff3cbe075aa286ab39ea5f43e7eac434c3383fa20eee57e6383fe62c4c"
original_class_hash = "0x32ac8ff3cbe075aa286ab39ea5f43e7eac434c3383fa20eee57e6383fe62c4c"
abi = "manifests/sepolia/abis/base/models/risingrevenant_components_game_game_phases.json"
name = "risingrevenant::components::game::game_phases"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "status"
type = "u8"
key = false

[[members]]
name = "preparation_block_number"
type = "u64"
key = false

[[members]]
name = "play_block_number"
type = "u64"
key = false
