kind = "DojoModel"
class_hash = "0x1f95a8e629e208b060027f511d260b974cf5d095c55e239ca17804bba08c147"
original_class_hash = "0x1f95a8e629e208b060027f511d260b974cf5d095c55e239ca17804bba08c147"
abi = "manifests/sepolia/abis/base/models/risingrevenant_components_game_game_map.json"
name = "risingrevenant::components::game::game_map"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "dimensions"
type = "Dimensions"
key = false
