kind = "DojoModel"
class_hash = "0x73b9456d1c1b0c8845497a4e767a9d267c870101e7998e1315a063620954b74"
original_class_hash = "0x73b9456d1c1b0c8845497a4e767a9d267c870101e7998e1315a063620954b74"
abi = "manifests/sepolia/abis/base/models/risingrevenant_components_reinforcement_reinforcement_market_consts.json"
name = "risingrevenant::components::reinforcement::reinforcement_market_consts"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "target_price"
type = "u128"
key = false

[[members]]
name = "decay_constant_mag"
type = "u128"
key = false

[[members]]
name = "max_sellable_percentage"
type = "u32"
key = false

[[members]]
name = "time_scale_mag_factor"
type = "u128"
key = false
