kind = "DojoModel"
class_hash = "0xc84297029bd2187b0495d4acd9e14ef64b310bfb34c08135ebc6a266410408"
original_class_hash = "0xc84297029bd2187b0495d4acd9e14ef64b310bfb34c08135ebc6a266410408"
abi = "manifests/sepolia/base/abis/models/rising_revenant-ERC20TotalSupplyModel-23e57e0f.json"
tag = "rising_revenant-ERC20TotalSupplyModel"
manifest_name = "rising_revenant-ERC20TotalSupplyModel-23e57e0f"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "total_supply"
type = "u256"
key = false
