kind = "DojoModel"
class_hash = "0x3618228ef8ba61db8ee0daa250ad9ea491c800b1f47190955e470af332f8198"
original_class_hash = "0x3618228ef8ba61db8ee0daa250ad9ea491c800b1f47190955e470af332f8198"
abi = "manifests/sepolia/abis/base/models/risingrevenant_components_trade_outpost_trade.json"
name = "risingrevenant::components::trade::outpost_trade"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "trade_id"
type = "u128"
key = true

[[members]]
name = "trade_type"
type = "u8"
key = false

[[members]]
name = "seller"
type = "ContractAddress"
key = false

[[members]]
name = "buyer"
type = "ContractAddress"
key = false

[[members]]
name = "price"
type = "u128"
key = false

[[members]]
name = "offer"
type = "Position"
key = false

[[members]]
name = "status"
type = "u8"
key = false
