kind = "DojoModel"
class_hash = "0x12cd74836f89d8f1febd9ff782dfacdaaa614e560a79c70e3ed9df6202973b4"
original_class_hash = "0x12cd74836f89d8f1febd9ff782dfacdaaa614e560a79c70e3ed9df6202973b4"
abi = "manifests/sepolia/abis/base/models/risingrevenant_components_game_dev_wallet.json"
name = "risingrevenant::components::game::dev_wallet"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "balance"
type = "u256"
key = false

[[members]]
name = "init"
type = "bool"
key = false
