[package]
cairo-version = "=2.7.0"
name = "rising_revenant"
version = "0.4.0"

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.5" }
origami_token = { git = "https://github.com/dojoengine/origami", tag = "v1.0.0-alpha.5" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.15.1" }

# origami_defi = { git = "https://github.com/dojoengine/origami", tag = "v1.0.0-alpha.3" }
# cubit = { git = "https://github.com/dojoengine/cubit", branch = "cairo_2.7" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.world.namespace]
default = "rising_revenant"

[tool.dojo.world]
name = "Rising Revenant"
description = "Rising Revenant"

[profile.sepolia]
