kind = "DojoModel"
class_hash = "0x2dd204a8425c24605677bc068b66c43b3a97db132acb8cff8b332fd7737006f"
original_class_hash = "0x2dd204a8425c24605677bc068b66c43b3a97db132acb8cff8b332fd7737006f"
abi = "manifests/dev/abis/base/models/risingrevenant_components_world_event_outpost_verified.json"
name = "risingrevenant::components::world_event::outpost_verified"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "event_id"
type = "u128"
key = true

[[members]]
name = "outpost_id"
type = "Position"
key = true

[[members]]
name = "verified"
type = "bool"
key = false
