kind = "DojoModel"
class_hash = "0x59c6d5980c90f5a8b95a6d651877e385b48f826aac23f2ca21752b1cee8b75d"
original_class_hash = "0x59c6d5980c90f5a8b95a6d651877e385b48f826aac23f2ca21752b1cee8b75d"
abi = "manifests/dev/abis/base/models/risingrevenant_components_game_game_trade_tax.json"
name = "risingrevenant::components::game::game_trade_tax"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "trade_tax_percent"
type = "u8"
key = false
