kind = "DojoModel"
class_hash = "0x7c4bf23b9cf792870afb64ed26310d5b9c12bf8fb8204341c612a32f8289ecf"
original_class_hash = "0x7c4bf23b9cf792870afb64ed26310d5b9c12bf8fb8204341c612a32f8289ecf"
abi = "manifests/dev/abis/base/models/risingrevenant_components_player_player_info.json"
name = "risingrevenant::components::player::player_info"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "outpost_count"
type = "u32"
key = false

[[members]]
name = "reinforcements_available_count"
type = "u32"
key = false

[[members]]
name = "init"
type = "bool"
key = false
