kind = "DojoModel"
class_hash = "0x7e4f76150c23bc5cb8da037bb334623345d61b8b6333b1cca3fa3fd152eb02e"
original_class_hash = "0x7e4f76150c23bc5cb8da037bb334623345d61b8b6333b1cca3fa3fd152eb02e"
abi = "manifests/dev/abis/base/models/risingrevenant_components_game_current_game.json"
name = "risingrevenant::components::game::current_game"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "u128"
key = false
