kind = "DojoModel"
class_hash = "0x1dedcb93628b96887ec772b05fe9e07ce7b1d3c94c49634301539ac51bc8743"
original_class_hash = "0x1dedcb93628b96887ec772b05fe9e07ce7b1d3c94c49634301539ac51bc8743"
abi = "manifests/dev/abis/base/models/risingrevenant_components_world_event_world_event_setup.json"
name = "risingrevenant::components::world_event::world_event_setup"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "radius_start"
type = "u32"
key = false

[[members]]
name = "radius_increase"
type = "u32"
key = false
