kind = "DojoModel"
class_hash = "0x5ca9df4337ad01cd1d7b8e4e43d67ff0a29a6925b1e494e78c9f478154885f3"
original_class_hash = "0x5ca9df4337ad01cd1d7b8e4e43d67ff0a29a6925b1e494e78c9f478154885f3"
abi = "manifests/dev/abis/base/models/risingrevenant_components_game_game_state.json"
name = "risingrevenant::components::game::game_state"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "outpost_created_count"
type = "u32"
key = false

[[members]]
name = "outpost_remaining_count"
type = "u32"
key = false

[[members]]
name = "remain_life_count"
type = "u32"
key = false

[[members]]
name = "reinforcement_count"
type = "u32"
key = false

[[members]]
name = "contribution_score_total"
type = "u256"
key = false
