#!/bin/bash
set -euo pipefail
pushd $(dirname "$0")/..

export RPC_URL="http://localhost:5050";
# export RPC_URL="https://api.cartridge.gg/x/rr-demo/katana";
# export RPC_URL="https://starknet-sepolia.public.blastapi.io/rpc/v0_6";

export WORLD_ADDRESS="0x403df785de33e6f468419bf138db7ccaccfbd6801e13e452a252df38b2b9657"

export GAME_ADDRESS="0x796bdacfdd83b316cb83560f2e0a471b37acc9b851af2dd0ce9c51668ea2b6d"

export WORLD_EVENT_ADDRESS="0xf15c94a9264d8a8b520ebd1a6ffd337758034bd5062c9c42f4b67163a9ad7c"

export OUTPOST_ACTIONS_ADDRESS="0x5e2e39c65bb8f60f2976796a304644a097b6201f810b6b2745ae03d90004937"

export REINFORCEMENTS_ACTIONS_ADDRESS="0x6ee2ef201d285ad87fa639427d35ac55b5af466ba9db1e2f5730e69bb81256d"

export TRADE_OUTPOST_ACTIONS_ADDRESS="0x257c0538f358fd138fe4c8d5df0620ce4c7539fa2b5bc7e19284eb2ddb2b562"

export TRADE_REINFORCEMENTS_ACTIONS_ADDRESS="0x2c85167ce5857a532fb23ef55fae7cb6a3cd2e81992c7ff0d6c691e83954580"


echo "---------------------------------------------------------------------------"
echo world : $WORLD_ADDRESS 
echo " "
echo game actions : $GAME_ADDRESS
echo " "
echo world event actions : $WORLD_EVENT_ADDRESS
echo " "
echo outpost actions : $OUTPOST_ACTIONS_ADDRESS
echo " "
echo reinforcements actions : $REINFORCEMENTS_ACTIONS_ADDRESS
echo " "
echo trade outpost actions : $TRADE_OUTPOST_ACTIONS_ADDRESS
echo " "
echo trade reinforcements actions : $TRADE_REINFORCEMENTS_ACTIONS_ADDRESS
echo "---------------------------------------------------------------------------"


# enable system -> models authorizations
sozo auth grant --world $WORLD_ADDRESS --wait writer \
 CurrentGame,$WORLD_ADDRESS \
 CurrentGame,$GAME_ADDRESS \
 CurrentGame,$WORLD_EVENT_ADDRESS \
 CurrentGame,$OUTPOST_ACTIONS_ADDRESS \
 CurrentGame,$REINFORCEMENTS_ACTIONS_ADDRESS \
 CurrentGame,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 CurrentGame,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 GamePhases,$WORLD_ADDRESS \
 GamePhases,$GAME_ADDRESS \
 GamePhases,$WORLD_EVENT_ADDRESS \
 GamePhases,$OUTPOST_ACTIONS_ADDRESS \
 GamePhases,$REINFORCEMENTS_ACTIONS_ADDRESS \
 GamePhases,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 GamePhases,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 GameMap,$WORLD_ADDRESS \
 GameMap,$GAME_ADDRESS \
 GameMap,$WORLD_EVENT_ADDRESS \
 GameMap,$OUTPOST_ACTIONS_ADDRESS \
 GameMap,$REINFORCEMENTS_ACTIONS_ADDRESS \
 GameMap,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 GameMap,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 GameERC20,$WORLD_ADDRESS \
 GameERC20,$GAME_ADDRESS \
 GameERC20,$WORLD_EVENT_ADDRESS \
 GameERC20,$OUTPOST_ACTIONS_ADDRESS \
 GameERC20,$REINFORCEMENTS_ACTIONS_ADDRESS \
 GameERC20,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 GameERC20,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 GameTradeTax,$WORLD_ADDRESS \
 GameTradeTax,$GAME_ADDRESS \
 GameTradeTax,$WORLD_EVENT_ADDRESS \
 GameTradeTax,$OUTPOST_ACTIONS_ADDRESS \
 GameTradeTax,$REINFORCEMENTS_ACTIONS_ADDRESS \
 GameTradeTax,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 GameTradeTax,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 GamePotConsts,$WORLD_ADDRESS \
 GamePotConsts,$GAME_ADDRESS \
 GamePotConsts,$WORLD_EVENT_ADDRESS \
 GamePotConsts,$OUTPOST_ACTIONS_ADDRESS \
 GamePotConsts,$REINFORCEMENTS_ACTIONS_ADDRESS \
 GamePotConsts,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 GamePotConsts,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 GameState,$WORLD_ADDRESS \
 GameState,$GAME_ADDRESS \
 GameState,$WORLD_EVENT_ADDRESS \
 GameState,$OUTPOST_ACTIONS_ADDRESS \
 GameState,$REINFORCEMENTS_ACTIONS_ADDRESS \
 GameState,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 GameState,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 GamePot,$WORLD_ADDRESS \
 GamePot,$GAME_ADDRESS \
 GamePot,$WORLD_EVENT_ADDRESS \
 GamePot,$OUTPOST_ACTIONS_ADDRESS \
 GamePot,$REINFORCEMENTS_ACTIONS_ADDRESS \
 GamePot,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 GamePot,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 DevWallet,$WORLD_ADDRESS \
 DevWallet,$GAME_ADDRESS \
 DevWallet,$WORLD_EVENT_ADDRESS \
 DevWallet,$OUTPOST_ACTIONS_ADDRESS \
 DevWallet,$REINFORCEMENTS_ACTIONS_ADDRESS \
 DevWallet,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 DevWallet,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 Outpost,$WORLD_ADDRESS \
 Outpost,$GAME_ADDRESS \
 Outpost,$WORLD_EVENT_ADDRESS \
 Outpost,$OUTPOST_ACTIONS_ADDRESS \
 Outpost,$REINFORCEMENTS_ACTIONS_ADDRESS \
 Outpost,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 Outpost,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 OutpostMarket,$WORLD_ADDRESS \
 OutpostMarket,$GAME_ADDRESS \
 OutpostMarket,$WORLD_EVENT_ADDRESS \
 OutpostMarket,$OUTPOST_ACTIONS_ADDRESS \
 OutpostMarket,$REINFORCEMENTS_ACTIONS_ADDRESS \
 OutpostMarket,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 OutpostMarket,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 OutpostSetup,$WORLD_ADDRESS \
 OutpostSetup,$GAME_ADDRESS \
 OutpostSetup,$WORLD_EVENT_ADDRESS \
 OutpostSetup,$OUTPOST_ACTIONS_ADDRESS \
 OutpostSetup,$REINFORCEMENTS_ACTIONS_ADDRESS \
 OutpostSetup,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 OutpostSetup,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 PlayerInfo,$WORLD_ADDRESS \
 PlayerInfo,$GAME_ADDRESS \
 PlayerInfo,$WORLD_EVENT_ADDRESS \
 PlayerInfo,$OUTPOST_ACTIONS_ADDRESS \
 PlayerInfo,$REINFORCEMENTS_ACTIONS_ADDRESS \
 PlayerInfo,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 PlayerInfo,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 PlayerContribution,$WORLD_ADDRESS \
 PlayerContribution,$GAME_ADDRESS \
 PlayerContribution,$WORLD_EVENT_ADDRESS \
 PlayerContribution,$OUTPOST_ACTIONS_ADDRESS \
 PlayerContribution,$REINFORCEMENTS_ACTIONS_ADDRESS \
 PlayerContribution,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 PlayerContribution,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 ReinforcementMarket,$WORLD_ADDRESS \
 ReinforcementMarket,$GAME_ADDRESS \
 ReinforcementMarket,$WORLD_EVENT_ADDRESS \
 ReinforcementMarket,$OUTPOST_ACTIONS_ADDRESS \
 ReinforcementMarket,$REINFORCEMENTS_ACTIONS_ADDRESS \
 ReinforcementMarket,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 ReinforcementMarket,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 OutpostTrade,$WORLD_ADDRESS \
 OutpostTrade,$GAME_ADDRESS \
 OutpostTrade,$WORLD_EVENT_ADDRESS \
 OutpostTrade,$OUTPOST_ACTIONS_ADDRESS \
 OutpostTrade,$REINFORCEMENTS_ACTIONS_ADDRESS \
 OutpostTrade,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 OutpostTrade,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 ReinforcementTrade,$WORLD_ADDRESS \
 ReinforcementTrade,$GAME_ADDRESS \
 ReinforcementTrade,$WORLD_EVENT_ADDRESS \
 ReinforcementTrade,$OUTPOST_ACTIONS_ADDRESS \
 ReinforcementTrade,$REINFORCEMENTS_ACTIONS_ADDRESS \
 ReinforcementTrade,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 ReinforcementTrade,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 WorldEventSetup,$WORLD_ADDRESS \
 WorldEventSetup,$GAME_ADDRESS \
 WorldEventSetup,$WORLD_EVENT_ADDRESS \
 WorldEventSetup,$OUTPOST_ACTIONS_ADDRESS \
 WorldEventSetup,$REINFORCEMENTS_ACTIONS_ADDRESS \
 WorldEventSetup,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 WorldEventSetup,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 WorldEvent,$WORLD_ADDRESS \
 WorldEvent,$GAME_ADDRESS \
 WorldEvent,$WORLD_EVENT_ADDRESS \
 WorldEvent,$OUTPOST_ACTIONS_ADDRESS \
 WorldEvent,$REINFORCEMENTS_ACTIONS_ADDRESS \
 WorldEvent,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 WorldEvent,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 CurrentWorldEvent,$WORLD_ADDRESS \
 CurrentWorldEvent,$GAME_ADDRESS \
 CurrentWorldEvent,$WORLD_EVENT_ADDRESS \
 CurrentWorldEvent,$OUTPOST_ACTIONS_ADDRESS \
 CurrentWorldEvent,$REINFORCEMENTS_ACTIONS_ADDRESS \
 CurrentWorldEvent,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 CurrentWorldEvent,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 OutpostVerified,$WORLD_ADDRESS \
 OutpostVerified,$GAME_ADDRESS \
 OutpostVerified,$WORLD_EVENT_ADDRESS \
 OutpostVerified,$OUTPOST_ACTIONS_ADDRESS \
 OutpostVerified,$REINFORCEMENTS_ACTIONS_ADDRESS \
 OutpostVerified,$TRADE_OUTPOST_ACTIONS_ADDRESS \
 OutpostVerified,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
 ReinforcementMarketConsts,$WORLD_ADDRESS \
    ReinforcementMarketConsts,$GAME_ADDRESS \
    ReinforcementMarketConsts,$WORLD_EVENT_ADDRESS \
    ReinforcementMarketConsts,$OUTPOST_ACTIONS_ADDRESS \
    ReinforcementMarketConsts,$REINFORCEMENTS_ACTIONS_ADDRESS \
    ReinforcementMarketConsts,$TRADE_OUTPOST_ACTIONS_ADDRESS \
    ReinforcementMarketConsts,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \
    WorldEventVerifications,$WORLD_ADDRESS \
    WorldEventVerifications,$GAME_ADDRESS \
    WorldEventVerifications,$WORLD_EVENT_ADDRESS \
    WorldEventVerifications,$OUTPOST_ACTIONS_ADDRESS \
    WorldEventVerifications,$REINFORCEMENTS_ACTIONS_ADDRESS \
    WorldEventVerifications,$TRADE_OUTPOST_ACTIONS_ADDRESS \
    WorldEventVerifications,$TRADE_REINFORCEMENTS_ACTIONS_ADDRESS \

 > /dev/null
 
echo "Default authorizations have been successfully set."